version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app 
      - node_modules:/app/node_modules   
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=posts_db
    depends_on:
      - db
      - cpp-backend

  cpp-backend:
    build:
      context: ./cpp-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /app
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posts_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  pgdata:
  node_modules:
